apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab-webservice.gitlab.svc.cluster.local/root/will-app.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true