Vagrant.configure("2") do |config|
  # Choix de la distribution (ex: Debian 11 ou Rocky Linux) 
  config.vm.box = "bento/debian-11"

  # Configuration du réseau avec IP statique imposée 
  config.vm.network "private_network", ip: "192.168.56.110"

  # Définition du nom de la VM : tonLogin + S 
  config.vm.hostname = "lle-pierS"

  # Configuration des ressources (1CPU/512MB suffisent généralement, mais 1024MB est plus confortable pour 3 apps)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Provisioning : Lancer le script d'installation de K3s
  config.vm.provision "shell", path: "scripts/server.sh"
end